language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t wanwanzainaer/docker-react-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true wanwanzainaer/docker-react-practice npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-west-1-074918240588'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
