language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t wanwanzainaer/docker-react-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true wanwanzainaer/docker-react-practice npm run test
